config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'messages#index'
  resources :messages, only: [:create, :destroy, :index, :new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: 'User'
	has_many :recipients
	has_many :users, :through => :recipients

	validates :sender_id, presence: true
	validates :body, presence: true

	def user_tokens=(ids)
	    self.user_ids = ids
	end
end

app/models/recipient.rb
class Recipient < ApplicationRecord
	belongs_to :message
	belongs_to :user

	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages, foreign_key: :sender_id
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!

	def new
		@message = Message.new
		@user = current_user.following
		@users = User.all
	end

	def create
		@message = current_user.messages.build(message_params)

		if @message.save
			flash[:success] = "Message Sent!"
			redirect_to root_path
		else
			flash[:alert] = "Sending Failed"
			render :new
		end
	end

	def index
		@messages = Recipient.where(:user_id => current_user.id).order("created_at DESC")
	end

	def new
		@message = Message.new
		@recipients = User.all
	end

	def destroy
		redirect_to destroy_user_session_path
	end

	private

		def message_params
			params.require(:message).permit(:body, :content, :title, :thumbnail_url, :sender_id, user_tokens: [])
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end

  

 end

app/views/layouts/_header.html.erb
<head>
  <style type="text/css">
  .logo{
    margin-top: 2px;
    background-color: #e7e7e7;
    color: #555555;
  }
  
    .navigation-wrapper{
       position: relative;
       padding: 15px 25px 15px 25px;
       @include linear-gradient(#0078D7, #2680C7)
    }

  .nav-link {
      padding-right: 1em;
      font-size: 20px;
      float: right;
    }

    h1{

      font-size: 35px;
      font-style: italic;
      font-family: Algerian ;
      color: #555555;
      text-align: center;
    }

    .button{
      background-color: #555555; 
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    }

  </style>
</head>
<body>
  <header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <div class="logo"><h1> Message App </h1> </div>
    <nav role="navigation">
        <% if user_signed_in? %>
           <span class="nav-link"> <%= link_to "New", new_message_path, class: 'button'%> </span>
          <span class="nav-link"> <%= link_to "Inbox", messages_path, class: 'button' %> </span>
          <span class="nav-link"> <%= link_to "Logout", destroy_user_session_path, :method => :delete , class: 'button' %> </span>
        <% else %>
          <span class="nav-link"><%= link_to "Sign In", new_user_session_path, class: 'button' %></span>
          <span class="nav-link"><%= link_to "Register", new_user_registration_path, class: 'button' %></span>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageApp</title>
    <style type="text/css">
      #flash{
              font-size: 18px;
              font-style: italic;
              color: #555555;
              margin-left: 40%;
      }
    </style>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= render 'layouts/header' %>
  
  	<% flash.each do |message_type, message| %>
			<div id="flash" class="flash-<%= message_type %>"><%= message %></div>
		<% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/_recipients.html.erb
<head>
	<style type="text/css">
		.btn{
				 background-color: #555555;; 
			    border: none;
			    color: white;
			    padding: 15px 32px;
			    text-align: center;
			    text-decoration: none;
			    display: inline-block;
			    font-size: 16px;
			    margin-left: 35%;
			}
			.text{
				      font-size: 15px;
				      font-style: italic;
				      font-family: Arial Black;
				      color: #555555;
				      margin-left: 5%;
				      padding-right: 25px;
				      padding-bottom: 10px;
				     }
	</style>
</head>
<body style="background-color: #e7e7e7;">
<div id="stream">
	<%= form_for :message, url: messages_path do |f| %>
	<span style="margin-left: 33.5%;">	<%= f.text_area :body,  id: "url", placeholder: "Message", class: "message_body", cols: '50', rows: '7' %> </span>
		<div id="stream-list" class="follow-list"> 
			<span class="text"> <h3 style="margin-left: 35%;"> Please choose receipients :  </h3></span>
		<table id="stream_item" style="margin-left: 35%;"> 
				<% @recipients.each do |user| %>
					<tr>
						<td class="text">	<%= check_box_tag "message[user_tokens][]", user.id, @message.users.include?(user), id: "user#{user.id}" %> </td>
						<td class="text">	<span class="list-group-item"><%= user.username %></span> </td>
							</tr>
					<br>
				<% end %>
				</table>
		</div>
		<br/> <br/>
		<div id ="stream-footer">
			<%= f.button :submit, class: "btn" %>
		</div>

	<% end %>
</div>
</body>

app/views/messages/index.html.erb
<head>
	<style type="text/css">
		table{
			margin-left: 38%;
			margin-top: 5%;
			font-size: 18px;
			font-style: italic;
			font-family: Berlin Sans FB;
		}
		td{
			padding-right: 20px;
			padding-left: 20px;
			padding-top: 20px;
			padding-bottom: 20px;
		}
	</style>
</head>
<body style="background-color: #e7e7e7;">
<div class="bigbox">
	<div class="box">
		<table border="1">
		<% @messages.each do |message| %>
			<tr>
					<td> <%= message.message.sender.username %> </td>
					<td> Message is : <br/> <br/> <%= message.message.body %></td>
			</tr>
		<% end %>
	</table>
	</div>
</div>
</body>

app/views/messages/new.html.erb
<div class="form-bigbox">
	<div class="form-box">
		<%= render 'messages/recipients' %>
	</div>
</div>